version: '3.8'
services:
  frontend:
    build:
      context: ./Frontend/keola-ecommerce
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  backend:
    build:
      context: ./KeolaEcommerce
      dockerfile: Dockerfile
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://localhost:5432/ecommerceKeola
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: root
      SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/ecommerceKeola
    depends_on:
      - postgres
      - mongodb
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerceKeola
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
